In [8]:
!pip install pydicom
!pip install numpy
!pip install matplotlib
!pip install opencv-python
!pip install tqdm
!pip install pandas
!pip install glob2
!pip install pylibjpeg
!pip install pylibjpeg-libjpeg==1.3.1

In [9]:
import DicomPipeLine 
import cv2
import numpy as np

In [10]:
main_data_source_path = r'C:\Users\vikra\Codes\Tumor_Codes\Final_Project_git\Liver tumor'

In [11]:
preprocessed_data_path = r'C:\Users\vikra\Codes\Tumor_Codes\Final_Project_git\Preprocessed'

In [12]:
sub_folders_to_scan_for = ['2','3','4','5']

In [13]:
path_obj = DicomPipeLine.Path_Settings(main_data_source_path, preprocessed_data_path, sub_folders_to_scan_for)

100%|████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<?, ?it/s]

- Found 2 folders with a total of 8 scans


In [14]:
# these are the attributes to extract from each patient
dcm_attributes_level_0 = [
    'PatientName',
    'PatientBirthDate',
    'PatientSex',
    'PatientSize',
    'PatientWeight',
    'StudyDate', 
    'StudyTime',
    'InstitutionAddress', 
    'InstitutionName',
    'Manufacturer', 
    'ManufacturerModelName'
]

# these are the attributes to extract from each scan per patient
dcm_attributes_level_1 = [
    'AcquisitionDate', 
    'AcquisitionTime', 
    'PatientPosition',
    'SeriesDescription',
    'SeriesDate',
    'SeriesTime'
]

# these are the attributes to extract from each frame per scan 
dcm_attributes_level_2 = [
    'Rows',
    'Columns',
    'InstanceNumber',
    'PixelSpacing',
    'ImagePositionPatient',
    'ImageOrientationPatient',
    'SliceLocation',
    'SliceThickness'
]

# specify all 3 levels of attributes in a array
dcm_attributes = [dcm_attributes_level_0, dcm_attributes_level_1, dcm_attributes_level_2]


In [15]:
dcm_to_numpy_obj = DicomPipeLine.DCM_Input_To_NPY_Output(path_obj, dcm_attributes)

In [16]:
path_obj.Refresh()

100%|████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<?, ?it/s]

- Found 2 folders with a total of 8 scans


In [17]:
dcm_to_numpy_obj.iterate(2)

- specified number of folders 2 exceeds total folders 0
- Hence processing only one folder


IndexError: pop from empty list

In [18]:
streamer = DicomPipeLine.Stream_Data(path_obj)

In [19]:
import time

def normalize(img_array):
    return cv2.normalize(img_array, dst=None, alpha=0, beta=65535, norm_type=cv2.NORM_MINMAX)

In [20]:
for ct_frame, pt_frame in zip(streamer.iter('1', 'CT PLAIN'), streamer.iter('1', 'PET WB  (AC)')):
    
    ct_frame = normalize(ct_frame)
    pt_frame = normalize(pt_frame)
    
    cv2.imshow('CT Image', ct_frame)
    cv2.imshow('PET Image', np.invert(pt_frame))
    
    print (ct_frame[300:340,240:270])
    
    time.sleep(0.2)

    cv2.waitKey(4)

cv2.destroyAllWindows()


C:\Users\vikra\Codes\Tumor_Codes\Final_Project_git\Preprocessed\1\CT PLAIN.pickle.gzip
C:\Users\vikra\Codes\Tumor_Codes\Final_Project_git\Preprocessed\1\PET WB  (AC).pickle.gzip
[[ 463  463  434 ... 2950 3037 3442]
 [ 752  694  694 ... 2169 2169 2024]
 [ 636  752  694 ... 2458 2256 2256]
 ...
 [1706 1909 1735 ... 1475 1475 1244]
 [1504 1793 1938 ... 1330 1620 1417]
 [1475 1620 1562 ... 1359 1359 1128]]
[[ 947  919  919 ... 3981 3814 3842]
 [ 947  807  612 ... 2923 3146 3369]
 [ 501  362  362 ... 1559 1754 2172]
 ...
 [1364 1503 1531 ... 1587 1615 1392]
 [1503 1615 1559 ... 1503 1726 1670]
 [1364 1559 1559 ... 1281 1308 1336]]
[[ 546  874  792 ... 2076 1858 2103]
 [ 901  656  901 ... 4917 5163 4808]
 [1120 1038 1175 ... 3469 3988 4371]
 ...
 [1393 1475 1339 ... 1202 1475 1448]
 [1311 1557 1284 ... 1229 1502 1502]
 [1284 1311 1612 ... 1120 1257 1120]]
[[ 160    0    0 ... 1173  826  826]
 [ 480  240  160 ... 3385 2585 1892]
 [ 906  800  426 ... 6236 5943 5810]
 ...
 [1333 1572 1279 ... 1

[[17572 17380 17315 ... 17315 16689 17010]
 [17074 17042 16560 ... 16737 16641 17107]
 [17396 17604 16834 ... 16882 17428 17107]
 ...
 [  932   867  1606 ...  4530  6007  7212]
 [ 1092  1333  1173 ...  2056  2329  2217]
 [  851  1060  1108 ...  7132  6457  6184]]
[[17816 18364 17633 ... 17451 16919 17384]
 [17998 17633 17235 ... 17882 17118 17567]
 [17949 17583 17666 ... 17899 17749 18081]
 ...
 [  980   913  1229 ...  9315 11075 12951]
 [  847   747  1179 ...  2275  3205  3669]
 [  531   681  1162 ...  2939  2955  3088]]
[[18278 18429 18178 ... 18061 17577 17561]
 [17711 18045 18262 ... 17227 17477 17878]
 [17277 17611 18646 ... 17310 17277 17594]
 ...
 [ 1102  1068  1552 ... 14856 16642 17210]
 [  868   835  1135 ...  5876  7862  8413]
 [  901  1135  1402 ...  1953  2287  2120]]
[[18766 18714 18542 ... 18300 18110 18231]
 [18214 18335 18835 ... 17955 18421 19181]
 [18714 19267 18732 ... 18076 18076 18473]
 ...
 [ 1416  1001  1364 ... 18922 18110 18283]
 [ 1088   984  1243 ... 12327 1

[[24381 24539 23706 ... 23931 23976 23729]
 [23639 24381 24021 ... 24449 24066 24269]
 [23751 24021 23954 ... 23954 23661 24134]
 ...
 [  833  1576  1981 ... 51374 57138 56777]
 [  405     0   901 ... 30978 37619 44485]
 [  360     0   788 ... 21860 22243 23661]]
[[25324 25206 24401 ... 24590 25845 25537]
 [26342 25206 25158 ... 24709 24874 24330]
 [25561 25419 25987 ... 24543 25206 25229]
 ...
 [  497  1089  2982 ... 51429 57701 59949]
 [    0   237  2769 ... 29537 36566 43974]
 [  521  1112   710 ... 23786 24543 23123]]
[[24035 23766 23497 ... 23541 24147 23743]
 [24393 25111 23743 ... 23811 23945 23452]
 [24012 24932 24035 ... 23026 23833 23385]
 ...
 [ 2399  1480  2309 ... 44168 52060 55917]
 [  919   538  1637 ... 26792 30940 35761]
 [ 1211    22   135 ... 22667 22308 21524]]
[[17484 17811 17500 ... 17026 16748 16731]
 [17026 17647 16895 ... 17614 16977 17304]
 [17533 17614 17614 ... 16862 17304 17304]
 ...
 [ 3320  1652  2617 ... 27084 33250 37977]
 [ 2682  1161  1734 ... 17467 1

[[25758 25593 24511 ... 22276 22088 22088]
 [25452 24723 23570 ... 22559 21382 20724]
 [25193 24934 24699 ... 22653 20700 20441]
 ...
 [  118   447   753 ... 24534 25758 26134]
 [  400   494   165 ... 25781 26063 26604]
 [ 2705   470   188 ... 26746 25640 25428]]
[[24515 24468 24305 ... 22163 21465 20813]
 [23956 24445 24561 ... 22373 22140 21162]
 [25050 25399 25259 ... 23094 22675 21488]
 ...
 [ 1048     0   605 ... 23816 25190 24584]
 [  698   210   535 ... 25516 25865 25492]
 [ 5122  1513   675 ... 25981 25748 24445]]
[[25872 25262 24816 ... 22869 22259 22119]
 [25051 24863 24581 ... 22987 22072 22306]
 [25707 25614 24628 ... 24300 23151 22635]
 ...
 [  305   352   586 ... 24323 26411 26341]
 [ 2181   704   633 ... 26223 27279 26857]
 [ 7482  4832  1783 ... 26458 27279 26012]]
[[25347 25418 25017 ... 22497 22073 22120]
 [25229 25017 24499 ... 23298 23251 22638]
 [25229 25441 25064 ... 24405 25700 24570]
 ...
 [  754   919     0 ... 25159 26172 26289]
 [ 4782  1272     0 ... 26549 2

[[22676 22394 23805 ... 23758 22606 23100]
 [22535 22253 23476 ... 23617 23805 23147]
 [22723 23264 23429 ... 22723 23170 23123]
 ...
 [ 1717  2046  1647 ... 25569 26181 25946]
 [ 2211  2070  1905 ... 26487 26840 26299]
 [ 1694  2211  2141 ... 26252 26863 26134]]
[[22688 21962 23180 ... 23343 24046 23882]
 [22688 22220 22313 ... 24022 24163 24069]
 [23063 23554 23554 ... 23250 23320 23109]
 ...
 [ 1779  2060  2248 ... 25896 26106 26013]
 [ 1990  1709  1452 ... 26434 26458 26411]
 [ 1428  1639  1920 ... 26715 26832 26762]]
[[23202 22473 22990 ... 23461 24590 23955]
 [22896 22614 22096 ... 24496 24237 23578]
 [22967 23296 22520 ... 24496 23626 24284]
 ...
 [ 2259  2118  1482 ... 25179 26638 26026]
 [ 2047  1883  1459 ... 25861 26873 26308]
 [ 1835  1600  1435 ... 26143 26849 27061]]
[[22622 22198 22151 ... 23705 23893 23658]
 [23093 23093 21563 ... 22834 23446 23093]
 [23093 23399 22010 ... 24034 23917 23563]
 ...
 [ 1695  1930  2166 ... 26176 26694 24882]
 [ 1695  2024  1789 ... 26741 2

[[28274 28916 27578 ... 26776 26669 27284]
 [27605 27311 25920 ... 27204 25117 25438]
 [26669 27364 27257 ... 27043 25412 25840]
 ...
 [27150 26749 27016 ... 26107 26374 25679]
 [26214 26401 27819 ... 26508 25679 24770]
 [25010 24823 25786 ... 25679 25117 24823]]
[[30721 29516 26853 ... 29208 29208 28619]
 [28535 28507 25760 ... 28731 27806 28311]
 [28647 28563 28142 ... 24891 25115 25031]
 ...
 [26517 26853 27470 ... 26881 26321 25872]
 [25199 25900 26321 ... 26853 26461 25844]
 [26685 26601 27217 ... 26012 26545 26993]]
[[29310 29393 27382 ... 28539 29503 28456]
 [27933 27713 27768 ... 28016 27437 26060]
 [30577 28649 27988 ... 25316 27602 27327]
 ...
 [26087 25702 25536 ... 25702 27079 26363]
 [25096 25647 25894 ... 26225 26859 26308]
 [26142 25894 25178 ... 25013 25013 25647]]
[[29962 28497 27889 ... 27005 25374 28138]
 [27170 28359 29243 ... 28055 27751 27281]
 [28829 28221 28884 ... 29603 28829 27005]
 ...
 [28497 28331 27253 ... 27005 27143 26452]
 [27115 27557 26839 ... 26009 2

[[ 7662  7180  5759 ... 31309 30497 31613]
 [ 7180  6546  5709 ... 32552 36484 35850]
 [ 9210  6267  7079 ... 31030 33237 40493]
 ...
 [26767 26006 25803 ... 25093 25296 24103]
 [25499 26437 25701 ... 24687 25270 26691]
 [24560 23773 22936 ... 25676 26310 26564]]
[[ 5043  4198  4250 ... 35327 31923 32793]
 [ 5811  5453  5478 ... 34687 37759 33510]
 [ 8883  7526  7424 ... 32153 36198 38220]
 ...
 [28006 27315 24985 ... 25574 25779 25523]
 [26035 26188 25651 ... 24268 26060 27110]
 [25932 26240 25932 ... 28441 28185 26624]]
[[ 4400  4555  4607 ... 37633 30956 30697]
 [ 4529  4478  5798 ... 39549 39601 32120]
 [ 6704  9033  9395 ... 34450 37685 36935]
 ...
 [26633 26426 24563 ... 26866 26426 26245]
 [26556 26556 27073 ... 27073 27746 28186]
 [27125 26685 26400 ... 24925 26193 25262]]
[[ 5992  5246  4287 ... 39012 34512 29825]
 [ 6178  6524  6817 ... 37228 40929 35657]
 [ 6631  9027  8974 ... 32621 35390 39438]
 ...
 [26736 27269 26230 ... 27242 27135 26044]
 [26816 27162 26656 ... 28174 2

[[ 4419  5472  6756 ... 14001  5035  2543]
 [ 6191  5318  6089 ...  8991  3597  3468]
 [ 8426  5703  5344 ...  5806  3083  3674]
 ...
 [17418  8452  8606 ... 31419 34039 34039]
 [12408  8966  8503 ... 34399 34399 32755]
 [12485  8401  7604 ... 37148 37276 36968]]
[[ 5515  6374  4969 ...  7935  6686  5906]
 [ 7050  7154  5307 ...  8273  4865  4709]
 [ 8377  6244  5932 ...  4007  3954  3512]
 ...
 [17743  8481  7727 ... 26094 26849 30777]
 [12176  7727  7545 ... 26224 29138 36033]
 [11109  8872  8794 ... 25990 33353 40872]]
[[ 5528  5219  3625 ...  3625  4551  4962]
 [ 5528  4885  4962 ...  6248  6068  5733]
 [ 5682  4474  5013 ...  4679  5656  4988]
 ...
 [19900 14218 13575 ... 22496 22959 24193]
 [14629  9487 10515 ... 21134 22034 23808]
 [11724  9924 10798 ... 21365 21519 22702]]
[[ 6381  5796  5158 ...  3722  3961  5051]
 [ 4546  5583  5849 ...  5264  4573  4945]
 [ 6460  5929  6035 ...  6195  6939  6726]
 ...
 [20817 12150  9199 ... 23901 24193 26108]
 [14064 10209  9837 ... 23795 2

[[12781  2600     0 ... 14551 21135 27359]
 [21163  3015   111 ... 15077 25312 29074]
 [27387  8631  3679 ... 17096 25119 28327]
 ...
 [ 8133 10208  8797 ... 35880 34828 33307]
 [11176 11729  9931 ... 35548 33058 31287]
 [13168 10955 10346 ... 31481 30679 30292]]
[[ 9628    30     0 ... 15177 22765 29963]
 [24984  8128   240 ... 16076 25224 30533]
 [35452 22375 12507 ... 19406 28104 31403]
 ...
 [ 8848 11247 10648 ... 31163 34942 38931]
 [13347 12897 11487 ... 35602 40371 39801]
 [16106 12057  9868 ... 38331 39081 35422]]
[[21457 11057  7680 ... 14792 23548 28898]
 [31766 22473 13687 ... 16227 25312 31109]
 [34426 28927 23279 ... 19484 26776 34247]
 ...
 [ 7859  8965  9354 ... 27075 27224 31796]
 [ 8009  7471  9892 ... 27642 32394 40881]
 [11983 10519 11595 ... 30033 40941 43212]]
[[33167 32614 35501 ... 16768 26564 35562]
 [31969 33535 36146 ... 18794 30311 39800]
 [33658 34979 36299 ... 22326 30833 41090]
 ...
 [ 7155  7309 10472 ... 28683 29082 30403]
 [ 7892  8353 10226 ... 25551 2

[[12084  8157 11531 ... 45266 35367 31523]
 [ 9789  8019 11946 ... 44464 32961 30583]
 [16176  8544  9015 ... 46732 33708 30721]
 ...
 [16536 20075 24721 ... 38796 45432 42584]
 [22398 25440 27348 ... 41588 41727 32657]
 [25744 26629 29670 ... 42197 32823 28675]]
[[13963 12564  8998 ... 40846 33714 31739]
 [ 8531 11713 11494 ... 41697 32260 30916]
 [ 8778  9738 12838 ... 43397 32233 31300]
 ...
 [20437 23290 25512 ... 41559 48527 41477]
 [25676 27597 27130 ... 43672 40325 30861]
 [25951 27843 27542 ... 36731 29572 27898]]
[[12398 10383  9362 ... 35576 32597 33108]
 [ 9249 13533 17987 ... 38129 33250 31377]
 [12114 16823 25845 ... 37619 33420 32002]
 ...
 [21334 26072 28767 ... 47747 47605 37959]
 [25420 28030 28625 ... 45137 36342 27831]
 [28086 28200 28342 ... 31973 28597 29363]]
[[19142  9642  6381 ... 34965 32470 31534]
 [25862 19595 12251 ... 35220 33179 31307]
 [28925 27932 25097 ... 35561 32640 32385]
 ...
 [20248 23083 25919 ... 48152 42140 32612]
 [24870 27224 28613 ... 37461 3

[[ 6447  6039  8080 ... 34223 31557 32183]
 [ 6067  6366  5985 ... 34604 32672 32509]
 [ 6475  7726  7916 ... 33896 31802 32183]
 ...
 [53973 56422 57782 ... 26660 28075 27912]
 [48614 44452 39174 ... 27449 28238 27503]
 [31557 29979 27259 ... 25327 24593 26388]]
[[ 7760  8202  8313 ... 33996 30876 33251]
 [ 7567  7678  9169 ... 35129 30959 33140]
 [ 7871  7733  5882 ... 35267 33306 33582]
 ...
 [52196 57416 58299 ... 25656 26347 27230]
 [56670 49904 40707 ... 24579 23778 24993]
 [39271 33776 30379 ... 26319 26374 27783]]
[[ 6534  6506  8647 ... 35284 34394 36313]
 [ 7285  5811  7313 ... 33810 33532 33921]
 [ 7730  7785  7424 ... 38175 33449 32893]
 ...
 [51494 55998 49075 ... 27248 25636 25358]
 [54024 43430 32837 ... 25413 23133 24496]
 [37174 30251 28527 ... 25636 25691 27777]]
[[ 5782  6483  7447 ... 38988 39339 37294]
 [ 8119  5403  4468 ... 37411 37791 38141]
 [ 9287  8732  7038 ... 39280 36798 39660]
 ...
 [50349 43661 33673 ... 28416 27774 27715]
 [44508 35221 32329 ... 28328 2

[[27321 27084 27617 ... 32531 35668 36290]
 [27587 29837 27410 ... 36497 37681 38096]
 [29807 26403 27232 ... 47301 39990 41292]
 ...
 [30429 29689 31347 ... 33093 31672 33152]
 [29127 28742 29423 ... 30636 29304 31820]
 [29659 29630 30488 ... 31524 32856 33271]]
[[28742 26853 29266 ... 32840 33654 34729]
 [28568 26156 25371 ... 33480 35630 35863]
 [28016 27493 26708 ... 38856 35136 36299]
 ...
 [30399 30515 31445 ... 30079 32085 33915]
 [28481 29789 29672 ... 31125 31736 32201]
 [31532 30806 28597 ... 30631 30486 29091]]
[[26423 26104 29667 ... 37722 36447 35578]
 [26567 26828 26625 ... 35317 35810 39083]
 [29030 29291 27031 ... 36534 38475 38040]
 ...
 [31898 31522 33173 ... 29407 31203 32565]
 [28335 29494 31580 ... 30363 31058 30537]
 [31116 31580 30797 ... 30392 31580 31348]]
[[25408 25996 27871 ... 37580 38308 36909]
 [26052 27731 27199 ... 37916 36517 37413]
 [25884 25380 26332 ... 37021 37525 35818]
 ...
 [30669 28598 29158 ... 29186 29633 29913]
 [27787 28066 29410 ... 29466 2

[[25741 25658 25686 ... 41224 39547 40234]
 [26043 27226 25658 ... 31021 30554 30526]
 [25438 24476 25493 ... 28381 26539 28821]
 ...
 [31076 29454 29206 ... 30334 28904 27831]
 [30801 28739 29344 ... 29316 29976 28491]
 [28986 30334 28656 ... 29316 30554 30499]]
[[23800 23290 26633 ... 32102 32102 35898]
 [25047 26463 25443 ... 29920 27483 29863]
 [26463 25557 25103 ... 29013 26662 29523]
 ...
 [29863 30543 30458 ... 29240 31167 30572]
 [29693 31110 31082 ... 28900 29637 29297]
 [30118 29353 30317 ... 29438 30770 32300]]
[[26567 26680 27420 ... 29809 30833 34759]
 [26709 27249 26709 ... 27619 30577 31544]
 [25941 26538 27448 ... 28131 28131 27050]
 ...
 [30606 29752 30520 ... 31459 32341 30947]
 [30208 30833 30634 ... 31118 30805 31260]
 [31687 29326 29895 ... 32199 31402 31829]]
[[26891 26312 24894 ... 34736 36038 40612]
 [28194 27268 28339 ... 30597 31899 31436]
 [26081 26833 28570 ... 27412 29120 27644]
 ...
 [29815 27876 30249 ... 30249 30799 32420]
 [30770 32333 32912 ... 29728 3

[[31154 31606 32149 ... 34230 35949 40262]
 [33416 32240 32571 ... 35979 42071 48375]
 [33386 32783 31878 ... 39930 48676 48224]
 ...
 [31124 31968 31757 ... 32783 32903 32964]
 [29556 30913 32059 ... 30098 32632 31305]
 [31787 32632 33718 ... 30822 31094 29797]]
[[28856 30510 30230 ... 49327 51710 56085]
 [29809 32165 30538 ... 50112 51065 50168]
 [28996 28968 30398 ... 45569 46550 43830]
 ...
 [27874 29921 30426 ... 30033 31716 29865]
 [29108 30426 28996 ... 29613 30033 29388]
 [31351 30819 30903 ... 29416 30734 29501]]
[[26132 26847 26541 ... 41368 37106 39811]
 [25750 27766 28302 ... 42184 36544 39250]
 [27970 28021 27919 ... 41623 37999 37361]
 ...
 [26234 26541 27077 ... 27638 28761 27077]
 [26796 26132 26668 ... 27766 28710 26643]
 [26949 28225 27664 ... 26745 28046 25341]]
[[27349 27554 27786 ... 36234 35387 32357]
 [28838 28325 28068 ... 36851 35079 33512]
 [27041 27760 28993 ... 36542 34283 34873]
 ...
 [27786 27863 27683 ... 26887 27375 28222]
 [27632 26348 27606 ... 28428 2

[[27523 26600 26152 ... 30824 31663 31747]
 [27859 28950 27020 ... 27299 28362 31047]
 [24838 23719 24334 ... 32781 31019 30628]
 ...
 [28418 34739 43970 ... 30516 32054 31103]
 [27215 27495 38767 ... 29593 29537 27355]
 [25789 28250 34656 ... 29761 28530 30040]]
[[26752 27554 26752 ... 31135 32195 29531]
 [29302 28471 27297 ... 30390 29388 33971]
 [28958 25635 27612 ... 31536 30963 30705]
 ...
 [31851 37637 42993 ... 31249 31278 30562]
 [28385 26581 35231 ... 31450 30075 29502]
 [27383 27039 31765 ... 30505 29903 30075]]
[[26262 27226 27279 ... 27413 27413 27092]
 [27039 28431 28912 ... 28297 28083 30010]
 [29261 27333 30117 ... 26664 26878 30171]
 ...
 [30653 39514 41896 ... 27788 28993 29100]
 [26182 29582 34909 ... 26958 25968 26235]
 [24281 23772 26851 ... 28243 28698 27601]]
[[26939 26112 28935 ... 25747 25479 23922]
 [26428 26866 29543 ... 25090 24214 25528]
 [26087 29373 31052 ... 24895 24360 23849]
 ...
 [33339 36990 34970 ... 25114 26112 25503]
 [25576 29884 36381 ... 25649 2

[[38077 38667 33304 ... 28021 26868 23597]
 [33545 38023 34752 ... 25393 24428 24455]
 [28933 35637 38130 ... 23704 24562 26037]
 ...
 [26707 28048 34055 ... 31025 32204 34698]
 [23651 23329 23597 ... 29496 30542 34564]
 [24509 23034 24669 ... 30140 32633 33813]]
[[33384 40168 36977 ... 25554 25045 24884]
 [30274 37835 39578 ... 27270 27029 27029]
 [24321 31373 41938 ... 25206 27056 27083]
 ...
 [27753 27270 31346 ... 31427 31749 32419]
 [25903 23972 23838 ... 30917 33974 34618]
 [23651 25018 24616 ... 32097 36575 36307]]
[[31731 38199 41986 ... 25512 25678 27336]
 [28055 34329 44501 ... 28801 29796 28663]
 [24019 30183 36872 ... 22997 26535 28829]
 ...
 [26369 27253 30294 ... 30598 29160 29243]
 [26037 25236 24904 ... 30460 31316 32284]
 [22941 25236 25705 ... 31676 34025 35545]]
[[23882 31967 41600 ... 26764 26363 25216]
 [23562 29512 39252 ... 25109 26097 25856]
 [24496 26470 34022 ... 23028 26097 28125]
 ...
 [26257 24816 25269 ... 30553 31433 31407]
 [24095 24229 24656 ... 31540 3

[[30184 27163 27558 ... 24254 24367 26485]
 [29196 25892 26033 ... 25807 25694 25892]
 [29393 28462 27078 ... 27106 26513 27332]
 ...
 [27247 29280 29450 ... 28800 27699 27050]
 [30156 31285 28687 ... 28546 26457 25525]
 [29083 27276 27219 ... 24057 25610 26909]]
[[30105 24979 27245 ... 24583 24413 25857]
 [29482 28463 28859 ... 24554 24781 26282]
 [33617 32286 28236 ... 25008 25716 27160]
 ...
 [29681 28548 28774 ... 28944 27896 26792]
 [31040 30020 30813 ... 26480 24809 25206]
 [30842 29284 29737 ... 25574 28406 29227]]
[[31034 27513 27813 ... 26094 25139 24620]
 [29424 28086 27622 ... 23173 23501 25412]
 [27841 29642 26722 ... 24238 25275 25548]
 ...
 [28114 29178 29861 ... 27459 27732 25684]
 [27240 28196 29151 ... 25057 26094 26067]
 [30434 31962 29833 ... 27568 27923 26858]]
[[29337 28243 27816 ... 22957 25146 25013]
 [28269 27122 27389 ... 25280 24746 24799]
 [30058 31233 29150 ... 23278 22957 23384]
 ...
 [26214 26481 28136 ... 26374 25734 25226]
 [28003 27709 28109 ... 25974 2

[[32139 33048 32086 ... 26497 25267 24652]
 [32540 33128 33128 ... 25214 24759 23770]
 [30241 32647 33342 ... 25909 26150 26016]
 ...
 [27647 27086 28289 ... 25722 25936 25963]
 [26417 28209 29011 ... 26765 26738 25374]
 [25936 26497 25562 ... 26043 25481 25054]]
[[35261 35261 33374 ... 23966 23103 22618]
 [33024 34776 36366 ... 25637 26500 25853]
 [31271 34237 35423 ... 25368 25206 24694]
 ...
 [25880 27982 26742 ... 24828 25287 25502]
 [27416 28576 27713 ... 26203 25826 25529]
 [26904 27174 27821 ... 27416 27470 25341]]
[[36894 36518 30731 ... 26578 26284 24944]
 [34670 37510 34589 ... 25614 24864 24756]
 [34938 37697 38019 ... 24623 24301 24462]
 ...
 [35688 34134 30410 ... 23899 22720 24194]
 [30865 30731 28481 ... 27195 26980 26016]
 [27918 28641 27489 ... 26712 25105 24542]]
[[37764 37606 27140 ... 26877 23747 22248]
 [37238 30138 29112 ... 25194 22958 22406]
 [35581 32426 33425 ... 23958 23642 24142]
 ...
 [46101 46364 45443 ... 25851 25036 24957]
 [31242 33767 32741 ... 25798 2

[[23811 23219 23391 ... 23219 22503 23367]
 [24748 24280 22996 ... 23219 22799 22577]
 [25020 24798 23638 ... 23589 23515 24576]
 ...
 [23367 24181 24354 ... 21985 21861 23712]
 [25118 24650 25686 ... 22799 23293 24378]
 [24403 24477 24378 ... 24477 24280 23638]]
[[25291 25365 26105 ... 25415 25341 24057]
 [24354 25291 25513 ... 22380 22133 22306]
 [25390 26352 25563 ... 23021 22552 23317]
 ...
 [24107 23786 24428 ... 22774 23317 25118]
 [26229 25341 24181 ... 24230 23860 23786]
 [23786 24921 25316 ... 21343 21319 21935]]
[[24355 25921 26890 ... 23634 24952 24057]
 [26542 26915 25747 ... 24430 23933 23411]
 [26965 27014 27039 ... 26070 23833 24231]
 ...
 [23982 24703 24852 ... 24181 24454 24579]
 [25722 23982 24181 ... 23262 23460 24206]
 [24579 24579 25747 ... 21124 22019 24305]]
[[24839 26484 26239 ... 22115 23121 22606]
 [25109 25846 25502 ... 23809 24447 23931]
 [27049 26410 26386 ... 22925 22925 23097]
 ...
 [23980 24545 24005 ... 24447 23563 23121]
 [25281 23416 24839 ... 24815 2

[[25162 24298 24273 ... 22051 22619 22643]
 [26347 26817 27039 ... 23014 22224 22446]
 [27187 26496 26496 ... 20890 21088 22841]
 ...
 [24051 23853 23681 ... 22520 22569 23211]
 [22964 22717 23038 ... 23261 22792 24125]
 [22495 22940 23557 ... 22619 23335 25261]]
[[26040 24277 24277 ... 23431 22972 22344]
 [28069 27296 26644 ... 20943 21644 22537]
 [24591 23794 24542 ... 21692 20967 20726]
 ...
 [21450 21813 22682 ... 22103 21813 21934]
 [21644 22175 22682 ... 21233 22030 22248]
 [23407 24011 22586 ... 22537 23383 23455]]
[[26709 26023 26023 ... 22596 23306 22865]
 [24872 23771 25117 ... 23281 23110 22669]
 [26194 25656 26464 ... 24236 24579 23232]
 ...
 [22547 22057 22057 ... 21323 21886 22400]
 [22008 22571 23771 ... 21690 22596 22987]
 [23844 23036 23134 ... 23771 23697 24750]]
[[26391 25259 25530 ... 22698 23831 23363]
 [25825 24693 26416 ... 22132 22378 23068]
 [25431 25702 26465 ... 22058 22822 21886]
 ...
 [23363 22428 22378 ... 23092 24323 24668]
 [21763 21664 21615 ... 22969 2

[[25263 26147 25621 ... 21749 21630 22682]
 [24785 24833 25358 ... 21797 21749 22395]
 [26075 25812 26171 ... 22514 21654 21702]
 ...
 [25717 25693 24761 ... 22729 25789 26553]
 [26219 25956 25502 ... 24833 27294 23136]
 [24498 24976 25311 ... 25908 25693 16802]]
[[24904 26000 25781 ... 21764 22567 22859]
 [27728 27509 28045 ... 22835 23273 23809]
 [26073 25026 24856 ... 21837 22275 23005]
 ...
 [26000 26974 26438 ... 23565 26146 25123]
 [26292 26121 25586 ... 25196 27168 20498]
 [26048 25854 26170 ... 27193 24466 14704]]
[[26521 26204 25814 ... 21666 21642 21471]
 [26009 26717 27278 ... 22959 23618 23716]
 [26180 25716 25765 ... 21398 20715 22642]
 ...
 [26643 26863 26814 ... 24008 26351 23740]
 [25155 25350 25228 ... 26375 27595 18787]
 [25375 25741 26595 ... 28107 23984 13371]]
[[26631 26170 25467 ... 21950 21829 22096]
 [25637 26292 26243 ... 21756 22096 22168]
 [25394 25491 25224 ... 21101 21756 21586]
 ...
 [26413 26219 26243 ... 24642 26607 21053]
 [24521 24982 25734 ... 26922 2

In [24]:
i=0
for ct_frame in streamer.iter('1', 'CT PLAIN'):

    if i>=280 and i<=430:
        
        ct_frame = normalize(ct_frame)
    
        cv2.imshow('CT Image', np.invert(ct_frame))
        #cv2.imshow('PET Image', np.invert(pt_frame))
    
        print (ct_frame[300:340,240:270])
    
        time.sleep(0.1)
        
    i=i+1

    cv2.waitKey(4)

cv2.destroyAllWindows()


C:\Users\vikra\Codes\Tumor_Codes\Final_Project_git\Preprocessed\1\CT PLAIN.pickle.gzip
[[ 8585  8736 11850 ... 45252 49816 46491]
 [ 6650  7345  9461 ... 45554 49605 47307]
 [ 5653  6892  8252 ... 42350 50632 49363]
 ...
 [11003  9159  8011 ... 31619 32072 30984]
 [11245 10822  9129 ... 30893 32193 31710]
 [12303 12605 10580 ... 30561 31619 31165]]
[[ 8285  8470 13200 ... 42783 43525 37775]
 [ 7512  7388 12581 ... 45102 42443 40372]
 [ 7512  6770 12334 ... 44267 43742 40867]
 ...
 [10510 11438 11994 ... 32737 31593 31809]
 [12025 14034 13292 ... 34870 34560 35395]
 [11654 13323 13107 ... 31809 32149 32891]]
[[ 7797  8334 11112 ... 43280 46721 39239]
 [ 7703  8018 10007 ... 44795 43311 36366]
 [ 8997  8302 11459 ... 47731 46373 37440]
 ...
 [12596 13195 18341 ... 32641 31978 32105]
 [12564 13732 18057 ... 33746 31978 32231]
 [15089 14206 17078 ... 32294 30968 33020]]
[[ 6572  4495  6200 ... 38069 45881 39402]
 [ 7130  6758  7719 ... 43680 45292 36519]
 [10168  8897  6882 ... 47369 47400

[[ 6780  7828  6402 ... 33029 34484 34455]
 [ 5907  4452  5529 ... 33059 33059 33961]
 [ 5820  4307  5296 ... 33088 33408 33670]
 ...
 [30585 31080 31691 ... 29887 30730 30614]
 [30789 30701 31109 ... 31138 31196 30410]
 [32535 30963 30265 ... 29857 31225 30236]]
[[11175  8752  6541 ... 33858 33858 34645]
 [ 9691  7722  8873 ... 34736 34100 35644]
 [ 8389  6935  6572 ... 35311 34463 36371]
 ...
 [31193 32495 31920 ... 32344 32283 33222]
 [32071 32495 32010 ... 33949 30890 31496]
 [33101 32616 32344 ... 32313 31496 32313]]
[[11703  9028  8268 ... 42555 41491 39151]
 [ 7326  7204  8511 ... 44531 44166 41886]
 [ 7204  6870  8724 ... 44835 44288 45260]
 ...
 [30731 30214 31035 ... 32342 32950 30974]
 [32190 32312 31612 ... 32616 33041 30701]
 [32312 31764 32372 ... 32190 30731 30184]]
[[12235  7546 10371 ... 38209 36796 39050]
 [11033  7906 10762 ... 38509 37848 39291]
 [ 6614  5411  8027 ... 38990 40403 41516]
 ...
 [31294 32046 33369 ... 30483 31655 32617]
 [32828 33579 32798 ... 31535 3

[[31329 26373 25405 ... 42237 36826 37168]
 [31472 25832 26915 ... 36997 35231 35288]
 [29449 28025 27484 ... 37253 35744 35231]
 ...
 [31215 32098 31158 ... 30418 30817 30076]
 [28880 28453 29535 ... 29706 30048 29449]
 [30361 29449 29250 ... 31586 31016 32839]]
[[31280 28395 25631 ... 42909 41707 37260]
 [30950 28305 28906 ... 43029 40234 37530]
 [30168 30198 29507 ... 42428 39513 39634]
 ...
 [31130 34555 33984 ... 31280 30709 32001]
 [29267 31791 31881 ... 31641 31010 32332]
 [31280 31821 31731 ... 32662 32662 33083]]
[[30909 28643 27042 ... 42119 40699 38614]
 [28250 28099 29338 ... 44083 40608 36499]
 [30426 29036 30426 ... 37677 38100 41635]
 ...
 [32299 32209 32783 ... 31816 29429 31332]
 [30819 31816 33296 ... 32722 30879 33478]
 [31937 31574 31363 ... 33417 31755 32632]]
[[27263 29685 30268 ... 48791 46276 43516]
 [29593 28735 29593 ... 46890 44130 40112]
 [31403 27845 28643 ... 42903 48546 48576]
 ...
 [33703 32292 33212 ... 31955 29655 33059]
 [33458 34868 34715 ... 30329 3

[[26428 25387 22676 ... 36615 33712 36232]
 [25250 24401 26291 ... 37519 36287 36643]
 [24511 23799 26619 ... 37656 37108 39436]
 ...
 [28701 28947 30755 ... 30618 29194 29084]
 [31056 31658 31823 ... 29933 29221 31412]
 [32124 30672 29632 ... 28892 30672 30399]]
[[24053 24356 24218 ... 34747 39008 36973]
 [24686 24686 26362 ... 37963 36644 36369]
 [24411 23256 22514 ... 36066 33180 34582]
 ...
 [28562 30183 31173 ... 28479 28397 30348]
 [30898 31256 30981 ... 27407 29524 28452]
 [30431 29111 28836 ... 27847 27902 28974]]
[[24932 22379 22270 ... 34655 37968 37833]
 [23112 24335 24606 ... 33704 35334 38647]
 [24470 27105 26181 ... 36665 35904 34628]
 ...
 [29223 28137 29549 ... 29712 29033 29441]
 [27838 28246 29359 ... 28300 28924 27865]
 [28653 29305 28897 ... 28354 28381 27458]]
[[24681 23163 23461 ... 39066 38877 36005]
 [23949 24085 24247 ... 35572 36466 36818]
 [26631 25683 24762 ... 35111 39364 38443]
 ...
 [27173 27986 28663 ... 32402 30072 29530]
 [28636 29367 29151 ... 29449 2

[[31059 31029 31269 ... 31838 31029 28660]
 [32588 30399 30579 ... 33277 33187 29440]
 [31598 30819 31119 ... 30129 30879 30699]
 ...
 [31658 32917 32138 ... 31568 31478 33547]
 [32498 30999 30039 ... 30699 31179 31688]
 [31838 30969 30369 ... 30309 31838 31808]]
[[32248 32065 33348 ... 30263 31638 28339]
 [31790 32737 32645 ... 33073 32768 29286]
 [33287 33164 30508 ... 32645 30996 32401]
 ...
 [33164 31485 30935 ... 34325 32279 31821]
 [30874 32035 29592 ... 33195 32004 31638]
 [31882 32248 29989 ... 32432 34020 32645]]
[[30773 31085 29529 ... 27436 25060 25937]
 [31565 30519 29359 ... 30943 29925 26446]
 [30434 29274 30462 ... 30547 30208 28963]
 ...
 [30010 31509 30010 ... 30123 30434 31113]
 [32075 30151 29076 ... 29868 30689 30406]
 [31396 30660 28963 ... 29642 29670 29925]]
[[31932 33937 34636 ... 28560 28256 29289]
 [33603 33330 30382 ... 27678 26828 27132]
 [34636 32843 30322 ... 28438 27921 31203]
 ...
 [31962 33208 30504 ... 33299 31598 31932]
 [31264 31871 30413 ... 31902 3

In [ ]:
# prev_folder = None
# prev_scan = None
# for img_array, folder_name, scan_name in streamer.iterate_image_data(0, 1):
    
#     img_array = cv2.normalize(img_array, dst=None, alpha=0, beta=65535, norm_type=cv2.NORM_MINMAX)
#     cv2.imshow('View Window',img_array)
    
#     if folder_name != prev_folder or prev_scan != scan_name:
#         print(f'folder : {folder_name} | Scan : {scan_name}')
#         prev_folder = folder_name
#         prev_scan = scan_name

#     cv2.waitKey(2)